#!/usr/bin/env bash
# Bash script that Creates the
# file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill.
# Displays Y U no love me?
# Deletes the file /var/run/myscript.pid.

echo "$$" > /var/run/myscript.pid

delete_and_exit() {
    rm -f "/var/run/myscript.pid"
    exit
}

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'delete_and_exit' SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
