#!/usr/bin/env bash
# Script that displays Best School 10 times.
# for the 9th iteration, displays Hi before Best School.
k=0
while [ $k -lt 10 ]
do
  if [ $k == 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( k++ ))
done
