#!/usr/bin/env bash
# Script that displays bad luck for the 4 iteration, good luck for 8 
# other iteration Best School

k=1
while [[ $k -lt 10 ]]
do
	if [ $k == 3 ]; then
		echo "bad luck"
	elif [ $k == 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( k += 1))
done
