#!/usr/bin/env bash
# Script that displays information about the school file.

file_source="school"
if [ -e "$file_source" ]; then
	echo "school file exists"
	if [ -s "$file_source" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$file_source" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
