#!/usr/bin/env bash
# Script that resolve the ip address of both localhost and facebook.com
# localhost from 127.0.0.1 to 127.0.0.2
# facebook.com from 157.240.11.35 to 8.8.8.8

cp /etc/hosts ~/hosts.neu
sed -i "127.0.0.2/" ~/hosts.neu
sed -i "8.8.8.8\tfacebook.com" ~/hosts.neu
cp -f ~/hosts.new /etc/hosts
